//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstv3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> FK_company_id { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
