// <auto-generated />
namespace E_Commerce_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialv2));
        
        string IMigrationMetadata.Id
        {
            get { return "201702151311066_initialv2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
